[package]
name = "libp2p-server"
version = "0.12.0"
authors = ["Max Inden <mail@max-inden.de>"]
edition = "2021"
description = "A rust-libp2p server binary."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
base64 = "0.21"
env_logger = "0.10.0"
futures = "0.3.27"
futures-timer = "3"
libp2p = { git = "https://github.com/mxinden/rust-libp2p", branch = "rsa-keypair-protobuf", version = "0.52.1", default-features = false, features = ["autonat", "dns", "async-std", "noise", "tcp", "yamux", "identify", "kad", "ping", "relay", "metrics", "rsa", "macros"] }
libp2p-quic = { git = "https://github.com/mxinden/rust-libp2p", branch = "rsa-keypair-protobuf", version = "0.8.0-alpha", default-features = false, features = ["async-std"] }
log = "0.4"
prometheus-client = "0.21.2"
serde = "1.0.173"
serde_derive = "1.0.125"
serde_json = "1.0"
structopt = "0.3.26"
tide = "0.16"
zeroize = "1"

[patch.crates-io]
libp2p-identity = { git = "https://github.com/mxinden/rust-libp2p", branch = "rsa-keypair-protobuf" }


